sudo: false
dist: bionic
language: cpp
compiler: gcc

services:
  - docker

install: true

before_script:
  - cd extras/docker/arcemu_build
  - docker build -t arcemu_build .
  - cd ../../../

script:
  - mkdir bin
  - docker run -t -i -v `pwd`/bin:/srv/build/arcemu/bin arcemu_build
  - ls -la ./bin
